# Personal

cask "google-chrome"
cask "zed"
cask "ghostty"
cask "bitwarden"

brew "git"
brew "node"
brew "kubectl"
brew "k9s"
brew "bitwarden-cli"

# Appwrite

cask "linear-linear"
cask "cloudflare-warp"

brew "doctl"
